# Default values for liberty-starter-icp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  cloudantPort: 80

image:
  repository: djccarew/liberty-starter
  tag: 1.0.4
  pullPolicy: Always

service:
  name: liberty-starter-web
  type: NodePort
  internalPort: 9080


embedded-cloudant:
  replicaCount: 1
  service:
    name: liberty-starter-cloudant
    type: ClusterIP
  image:
    repository: ibmcom/cloudant-developer
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
