---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
    cloudant-host: {{ .Release.Name }}-cloudant-service
    cloudant-port: "{{ .Values.global.cloudantPort }}"
