apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-deployment
  labels:
    app: {{ .Release.Name }}-app
    tier: frontend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
        tier: frontend
    spec:
      containers:
      - name: {{ .Release.Name }}-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.internalPort }}
        env:
        - name: CLOUDANT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: cloudant-username
        - name: CLOUDANT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: cloudant-password
        - name: CLOUDANT_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: cloudant-host
        - name: CLOUDANT_PORT
          valueFrom:
              configMapKeyRef:
                 name: {{ .Release.Name }}-configmap
                 key: cloudant-port
