---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
    cloudant-host: {{ .Values.cloudantService }}
    cloudant-port: "{{ .Values.cloudantPort }}"
    cloudant-db-name: {{ .Values.cloudantDbName }}
