apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-deployment
  labels:
    app: "{{ .Release.Name }}-app"
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-app"
        tier: frontend
    spec:
      containers:
      - name: "{{ .Release.Name }}-web"
        image: jzaccone/guestbook
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9080
        env:
        - name: CLOUDANT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretsConfig }}
              key: cloudant-username
        - name: CLOUDANT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretsConfig }}
              key: cloudant-password
        - name: CLOUDANT_HOST
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-configmap"
              key: cloudant-host
        - name: CLOUDANT_PORT
          valueFrom:
              configMapKeyRef:
                 name: "{{ .Release.Name }}-configmap"
                 key: cloudant-port
        - name: CLOUDANT_DB_NAME
          valueFrom:
              configMapKeyRef:
                 name: "{{ .Release.Name }}-configmap"
                 key: cloudant-db-name
