apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
  labels:
    app: {{ .Release.Name }}-app
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 9080
    protocol: TCP
    name: {{ .Release.Name }}-web-service
  selector:
    app: {{ .Release.Name }}-app
    tier: frontend
