apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudant-deployment
  labels:
    app: liberty-starter
    tier: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: liberty-starter
        tier: database
    spec:
      containers:
      - name: cloudant-deployment
        image: ibmcom/cloudant-developer
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
