apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cloudant-deployment
  labels:
    app: "{{ .Release.Name }}-liberty-starter"
    tier: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-liberty-starter"
        tier: database
    spec:
      containers:
      - name: {{ .Release.Name }}-cloudant
        image: ibmcom/cloudant-developer
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
