apiVersion: v1
kind: Service
metadata:
  name: cloudant-service
  labels:
    app: liberty-starter
    tier: database
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: liberty-starter
    tier: database
